### ISSUE TITLE
Missing step for migration from source to docker

### ISSUE THREAD

**Issue by hborchardt** [passbolt/passbolt_help#72]
Hi 👋 

Today I was attempting an upgrade of passbolt from source to docker with this guide:
https://help.passbolt.com/hosting/upgrade/ce/migrate-existing-ce-to-docker.html

I spent a lot of time figuring out that I also need to put the server public key fingerprint into the
`docker-compose.yml` file as an environment variable:
```
services:
  passbolt:
    environment:
      PASSBOLT_GPG_SERVER_KEY_FINGERPRINT: "theKeyFingerprintFromTheOldConfig"
```

Would be nice to see this integrated into the guide 😃
